<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <Product>wslc-docker-socket</Product>
    <Authors>pengweiqhca</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <DebugType>embedded</DebugType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <NoWarn>CS1591;NU1008;NU1010;NU1507</NoWarn>
  </PropertyGroup>
</Project>
