<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RollForward>Major</RollForward>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    <!-- Needed for NotifyIcon/SetWinEventHook so the console window can minimize to the system tray. -->
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WslcDockerSocket.Tests" />

    <!--<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />-->
    <PackageReference Include="Swashbuckle.AspNetCore" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="System.Management" />
  </ItemGroup>

</Project>
